### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by anpShawn** [grapefrukt/extension-ios-audio#1]
Hi, I'm building on OSX Yosemite, OpenFL 2.2.7

When I try to compile the extension with my project I receive the following errors:

Classes/Main.mm:39:30: error: expected ';' after top level declarator
     extern "C" int extension-ios-audio_register_prims();
                             ^
                             ;
Classes/Main.mm:78:21: error: use of undeclared identifier 'audio_register_prims'; did you
      mean 'std_register_prims'?
      extension-ios-audio_register_prims();
                    ^~~~~~~~~~~~~~~~~~~~
                    std_register_prims

Classes/Main.mm:15:21: note: 'std_register_prims' declared here
     extern "C" int std_register_prims();
                    ^
Classes/Main.mm:78:17: error: use of undeclared identifier 'ios'
      extension-ios-audio_register_prims();

I'm weak with Objective C/C++, so I was not sure if this was an easy fix or not.
Thanks!

**Comment by player-03** [comment]
Like Haxe, C++ accepts underscores and alphanumeric characters in variable names. However, the hyphens in "`extension-ios-audio`" aren't allowed.

This is why it looked at the line "`extension-ios-audio_register_prims()`" and complained that "`audio_register_prims`" was undeclared.

**Comment by grapefrukt** [comment]
It's possible that the generation of that particular line was changed in some version of Lime/OpenFL, because in my project it's `extension_ios_audio_register_prims()` 

I use Lime 2.7.0, OpenFL 3.4.0, hxcpp 3.2.180 and XCode 7.2.1

I also suppose that doing a project wide replace to get rid of the dashes may work. It's unfortunately not something I have time to investigate.

**Comment by anpShawn** [comment]
Some updates for clarification:

I was trying to build with openFL 2.2.7, lime 2.1.2. 
As suggested by player03, I updated to lime 2.3.1 and was able to incorporate the extension. However, I still failed in the last steps because I had not chosen to update openFL as well. I'm not able to update openFL at this time because this project is already in release and I froze updates to ensure compatibility.

I was however able to pick out the relevant bits of this extension (in the .mm file) and incorporate them into my own proprietary extension.

**Comment by ben-farrant** [comment]
Fixed in https://github.com/grapefrukt/extension-ios-audio/pull/2

**Comment by player-03** [comment]
This wasn't strictly necessary, as Lime has been able to handle hyphens since version 2.3.1. On the other hand, it doesn't hurt.
